try {
    var numero=5
    print(nome)
    print(numero)
} catch (error) {
    print("Ocorreu um erro: " + error.message)
}